### ISSUE TITLE
Ollama models are not working.

### ISSUE THREAD

**Issue by owenzhao** [kspviswa/pyOllaMx#2] opened 2024-04-09 09:07 UTC
Generic Error Occured

<img width="984" alt="截屏2024-04-09 17 06 15" src="https://github.com/kspviswa/pyOllaMx/assets/2182896/73206bf5-8ff9-4e36-9f17-465dc98f7022">

**Comment by kspviswa** [comment] 2024-04-11 06:52
Hi do you see issues only with Gemma model?

**Comment by owenzhao** [comment] 2024-04-11 12:04
> Hi do you see issues only with Gemma model?

No. All Ollama model are list correctly, but cannot be used. 

Also, there is no model for mlx after enable "Load mlx models from HF".  Do I have do to something first to get mlx working?

I have installed 

<img width="470" alt="截屏2024-04-11 20 04 20" src="https://github.com/kspviswa/pyOllaMx/assets/2182896/4229f4f1-a769-46fd-86f4-0445ad8c87e3">

**Comment by kspviswa** [comment] 2024-04-11 15:09
For MLX models, you need to download some via Hugging Face. Once the models are in hf cache in local system, it should automatically be discovered once you enabled that HF toggle.

Reg ollama issue, is ollama api server running in background ?

**Comment by owenzhao** [comment] 2024-04-11 16:32
Ollama runs, and other clients work well.

**Comment by kspviswa** [comment] 2024-04-11 16:34
Ok let me give you another build that shows exact error and other diagnostics information.

**Comment by kspviswa** [comment] 2024-04-13 19:31
![Screenshot 2024-04-13 at 2 30 00 PM](https://github.com/kspviswa/pyOllaMx/assets/7476271/dd666fa5-87c3-4aaf-aaf8-1004d9117580)

I couldn't reproduce the issue. I'm able to see PyOllaMx clearly mentioning the error string and also supports chinese characters. Can you tell me more about the issue? When do you see this?

**Comment by owenzhao** [comment] 2024-04-14 02:00
It works here too. I didn't know why. Maybe Ollama got a new version. It is 0.1.31.

<img width="984" alt="截屏2024-04-14 09 59 27" src="https://github.com/kspviswa/pyOllaMx/assets/2182896/c1bbe1c6-b40c-41dc-b0c4-cae51db8221a">

**Comment by owenzhao** [comment] 2024-04-14 02:01
I still don't know how to get mlx to download models. Can you make it easier in your app?

**Comment by kspviswa** [comment] 2024-04-14 02:02
Yes I'm currently working on that feature to streamline the download process.

**Comment by kspviswa** [comment] 2024-04-14 02:03
If your ollama issue is resolved, can you close this issue?

**Closed** 2024-04-14 02:04 UTC
